package vendingmachine;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.DecimalFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author   Nome: Gabriel Ribeiro Dourado   Matricula: 201703074181
 *           Nome: Cristian Rogério Arioli   Matricula: 201702533531
 */
public class VendingMachine extends javax.swing.JFrame {

    /**
     * Creates new form VendingMachine
     */
    public VendingMachine() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    Caixa caixa = new Caixa(30, 30, 30, 30, 30);
    
    Produto CocaCola = new Produto ("001", "Coca-Cola", 2.50, 20);
    Produto Kuat = new Produto ("002", "Kuat", 2.25, 20);
    Produto Pepsi = new Produto ("003", "Pepsi", 1.95, 20);
    Produto Fanta = new Produto ("004", "Fanta", 3.00, 20);
    Produto Guarana = new Produto ("005", "Guaraná", 2.75, 20);
    Produto Sprite = new Produto ("006", "Sprite", 2.20, 20);
    
    DecimalFormat df = new DecimalFormat("0.00");
    
    public void attTabela(){
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        Vector v = new Vector();
        v.add(CocaCola.getCodigo());
        v.add(CocaCola.getNomeProd());
        v.add("R$ " + df.format(CocaCola.getPreco()));
        v.add(CocaCola.getQuant());
        dtm.addRow(v);

        Vector v2 = new Vector();
        v2.add(Kuat.getCodigo());
        v2.add(Kuat.getNomeProd());
        v2.add("R$ " + df.format(Kuat.getPreco()));
        v2.add(Kuat.getQuant());
        dtm.addRow(v2);

        Vector v3 = new Vector();
        v3.add(Pepsi.getCodigo());
        v3.add(Pepsi.getNomeProd());
        v3.add("R$ " + df.format(Pepsi.getPreco()));
        v3.add(Pepsi.getQuant());
        dtm.addRow(v3);

        Vector v4 = new Vector();
        v4.add(Fanta.getCodigo());
        v4.add(Fanta.getNomeProd());
        v4.add("R$ " + df.format(Fanta.getPreco()));
        v4.add(Fanta.getQuant());
        dtm.addRow(v4);
        
        Vector v5 = new Vector();
        v5.add(Guarana.getCodigo());
        v5.add(Guarana.getNomeProd());
        v5.add("R$ " + df.format(Guarana.getPreco()));
        v5.add(Guarana.getQuant());
        dtm.addRow(v5);
        
        Vector v6 = new Vector();
        v6.add(Sprite.getCodigo());
        v6.add(Sprite.getNomeProd());
        v6.add("R$ " + df.format(Sprite.getPreco()));
        v6.add(Sprite.getQuant());
        dtm.addRow(v6);
    }
    
    public void attTudo(){
        attTabela();
        codigoProduto.setText(null);
        saldo.setText("R$ " + df.format(caixa.getSaldoAtual()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        AdicionarBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        saldo = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codigoProduto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        ComprarBtn = new javax.swing.JButton();
        CancelarBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VendingMachine");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentShown(evt);
            }
        });

        jLabel5.setText("Valor da Moeda:");

        AdicionarBtn.setText("Adicionar");
        AdicionarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Saldo:");

        saldo.setEditable(false);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.05", "0.10", "0.25", "0.50", "1.00" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jComboBox1VetoableChange(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("Produtos:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Adicionar Moedas:");

        codigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoProdutoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Preço", "Qntd Disp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(10);
        }

        jLabel3.setText("Digite o código do produto:");

        ComprarBtn.setText("Comprar");
        ComprarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarBtnActionPerformed(evt);
            }
        });

        CancelarBtn.setText("Cancelar");
        CancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Admin Mode");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(codigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ComprarBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CancelarBtn)))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(30, 30, 30)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(AdicionarBtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdicionarBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(codigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComprarBtn)
                    .addComponent(CancelarBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdicionarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarBtnActionPerformed
        double doublecombobox = Double.parseDouble(jComboBox1.getSelectedItem().toString());
        caixa.setSaldoAtual(doublecombobox);
        
        attTudo();
    }//GEN-LAST:event_AdicionarBtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void codigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoProdutoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        codigoProduto.setText((String)jTable1.getValueAt(jTable1.getSelectedRow(), 0));
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox1VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jComboBox1VetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1VetoableChange

    private void jPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2ComponentShown

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        attTabela();
    }//GEN-LAST:event_formWindowActivated

    private void CancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBtnActionPerformed
        caixa.cleanerAtual();
        
        attTudo();
    }//GEN-LAST:event_CancelarBtnActionPerformed

    private void ComprarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarBtnActionPerformed
        if (codigoProduto.getText().equals(CocaCola.getCodigo())){
            if(caixa.getSaldoAtual() >= CocaCola.getPreco() && CocaCola.getQuant() > 0){
                caixa.comprar(CocaCola);
            }
            else{
                if (caixa.getSaldoAtual() < CocaCola.getPreco())
                JOptionPane.showMessageDialog(null, "Saldo insuficiente", "Saldo insuficiente", JOptionPane.ERROR_MESSAGE);
                
                if (CocaCola.getQuant() < 1)
                JOptionPane.showMessageDialog(null, "Produto indisponível", "Produto indisponível", JOptionPane.ERROR_MESSAGE);
            }
            attTudo();
        }
        else {
            if (codigoProduto.getText().equals(Kuat.getCodigo())){
                if(caixa.getSaldoAtual() >= Kuat.getPreco() && Kuat.getQuant() > 0){
                    caixa.comprar(Kuat);
                }
                else{
                    if (caixa.getSaldoAtual() < Kuat.getPreco())
                    JOptionPane.showMessageDialog(null, "Saldo insuficiente", "Saldo insuficiente", JOptionPane.ERROR_MESSAGE);

                    if (Kuat.getQuant() < 1)
                    JOptionPane.showMessageDialog(null, "Produto indisponível", "Produto indisponível", JOptionPane.ERROR_MESSAGE);
                }
                attTudo();
            }
            else {
                if (codigoProduto.getText().equals(Pepsi.getCodigo())){
                    if(caixa.getSaldoAtual() >= Pepsi.getPreco() && Pepsi.getQuant() > 0){
                        caixa.comprar(Pepsi);
                    }
                    else{
                        if (caixa.getSaldoAtual() < Pepsi.getPreco())
                        JOptionPane.showMessageDialog(null, "Saldo insuficiente", "Saldo insuficiente", JOptionPane.ERROR_MESSAGE);

                        if (Pepsi.getQuant() < 1)
                        JOptionPane.showMessageDialog(null, "Produto indisponível", "Produto indisponível", JOptionPane.ERROR_MESSAGE);
                    }
                    attTudo();
                }
                else {
                    if (codigoProduto.getText().equals(Fanta.getCodigo())){
                        if(caixa.getSaldoAtual() >= Fanta.getPreco() && Fanta.getQuant() > 0){
                            caixa.comprar(Fanta);
                        }
                        else{
                            if (caixa.getSaldoAtual() < Fanta.getPreco())
                            JOptionPane.showMessageDialog(null, "Saldo insuficiente", "Saldo insuficiente", JOptionPane.ERROR_MESSAGE);

                            if (Fanta.getQuant() < 1)
                            JOptionPane.showMessageDialog(null, "Produto indisponível", "Produto indisponível", JOptionPane.ERROR_MESSAGE);
                        }
                        attTudo();
                    }
                    else {
                        if (codigoProduto.getText().equals(Guarana.getCodigo())){
                            if(caixa.getSaldoAtual() >= Guarana.getPreco() && Guarana.getQuant() > 0){
                                caixa.comprar(Guarana);
                            }
                            else{
                                if (caixa.getSaldoAtual() < Guarana.getPreco())
                                JOptionPane.showMessageDialog(null, "Saldo insuficiente", "Saldo insuficiente", JOptionPane.ERROR_MESSAGE);

                                if (Guarana.getQuant() < 1)
                                JOptionPane.showMessageDialog(null, "Produto indisponível", "Produto indisponível", JOptionPane.ERROR_MESSAGE);
                            }
                            attTudo();
                        }
                        else {
                            if (codigoProduto.getText().equals(Sprite.getCodigo())){
                                if(caixa.getSaldoAtual() >= Sprite.getPreco() && Sprite.getQuant() > 0){
                                    caixa.comprar(Sprite);
                                }
                                else{
                                    if (caixa.getSaldoAtual() < Sprite.getPreco())
                                    JOptionPane.showMessageDialog(null, "Saldo insuficiente", "Saldo insuficiente", JOptionPane.ERROR_MESSAGE);

                                    if (Sprite.getQuant() < 1)
                                    JOptionPane.showMessageDialog(null, "Produto indisponível", "Produto indisponível", JOptionPane.ERROR_MESSAGE);
                                }
                                attTudo();
                            }
                            else {
                                JOptionPane.showMessageDialog(null, "Falha ao reconhecer o código", "Falha ao reconhecer o código", JOptionPane.ERROR_MESSAGE);
                                attTudo();
                                codigoProduto.requestFocus();
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_ComprarBtnActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        attTabela();
    }//GEN-LAST:event_formComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AdmMachine admMachine = new AdmMachine(caixa, CocaCola, Kuat, Pepsi, Fanta, Guarana, Sprite);
        AdmLogin caixaGUI = new AdmLogin(admMachine);
        caixaGUI.setLocationRelativeTo(VendingMachine.this);
        caixaGUI.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        attTudo();
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendingMachine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionarBtn;
    private javax.swing.JButton CancelarBtn;
    private javax.swing.JButton ComprarBtn;
    private javax.swing.JTextField codigoProduto;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField saldo;
    // End of variables declaration//GEN-END:variables
}
